export interface Product{
    id:number,
	product_name:string,
    image_path:string,
	id_category:number,
	category:string,
	id_sub_category:number,
	sub_category:string,
	id_brand:number,
	brand:string,
	price:number,
	stock_quantity:number,
	has_warranty:boolean ,
	warranty_duration_months:number,
    description:string,
	reference:string,
	image_id:number,
}