name: Deploy web app to AWS EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build --prod

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/eurodental_frontend

      - name: Download Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: Deploy to EC2 via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}  
          EC2_USER: ubuntu                   
        run: |
          scp -i ~/ssh_key -r dist/eurodental_frontend $EC2_USER@35.180.66.24:/home/ubuntu/app/eurodental_frontend
          ssh -i ~/ssh_key $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/app/eurodental_frontend/browser
            sudo systemctl restart nginx
            sudo systemctl status nginx
          EOF
