name: Deploy Angular App to EC2

on:
  push:
    branches:
      - master

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Zip the project
        run: |
          zip -r euro_dental_build.zip ./dist/eurodental_frontend

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: euro_dental_build
          path: euro_dental_build.zip

  deploy:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Download Project Zip
        uses: actions/download-artifact@v4
        with:
          name: euro_dental_build

      - name: Unzip project
        run: |
          unzip euro_dental_build.zip
          rm -f euro_dental_build.zip

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: '${{ secrets.EC2_SSH_PRIVATE_KEY }}'
          name: id_rsa
          known_hosts: '${{ secrets.EC2_HOST }}'

      - name: Copy app to EC2 instance
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/eurodental_frontend/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/eurodental_frontend/

      - name: Restart NGINX service
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo systemctl restart nginx
            sudo systemctl status nginx
          EOF
